#!/bin/bash

wifiinterface=wlan0
whereisiwconfig=/usr/sbin/iwconfig
whereisip=/usr/sbin/ip
bold=$(tput bold)
norm=$(tput sgr0)

function getwifiinfo { 
l2=`$whereisiwconfig $wifiinterface | sed -e s/"$wifiinterface.*IEEE 802.11abgn  ESSID:"//g | sed -e s/"          Mode:Managed  Frequency:"//g | sed -e s/"  Access Point:"//g | sed -e s/"          Bit Rate="//g | sed -e s/"          Retry short limit:7   RTS thr:off   Fragment thr:off"//g | grep -v Rx | grep -v Tx | grep -v Power |  tr -s '\n' ' '`
#echo -n " ${bold} bla ${norm}"
echo -n $l2 | sed "s/\(-[0-9]\{2\}\) dBm/${bold}\1${norm} dBm /"
#lees=`/usr/bin/ifconfig wlp2s0 | grep 'inet addr:'`
lees=`$whereisip a show dev $wifiinterface | grep 'inet '`
if [ `echo $lees | wc -c` -lt 4 ]
then
# newline 
	echo "***$lees***"
else
# ipadres
	#ip=`echo $lees | cut -d: -f2 | awk '{ print $1}'`

	ip=`echo $lees | awk '{ print $2}'`
	echo -n "$ip "

	tweedebyte=`echo $ip | awk -F\. '{ print $2}'`
	derdebyte=`echo $ip | awk -F\. '{ print $3}'`
	case $tweedebyte in

	23)	tijd=`ping -c 1 -w 1 10.23.255.155 | awk '{ print $7 }' | grep time`
	;;
	24)	tijd=`ping -c 1 -w 1 10.5.5.83     | awk '{ print $7 }' | grep time`
	;;
	27)	tijd=`ping -c 1 -w 1 10.27.255.254 | awk '{ print $7 }' | grep time`
	;;
	37)	tijd=`ping -c 1 -w 1 10.37.255.254 | awk '{ print $7 }' | grep time`
	;;
	40)	tijd=`ping -c 1 -w 1 10.40.255.254 | awk '{ print $7 }' | grep time`
	;;
	8)	tijd=`ping -c 1 -w 1 10.8.255.254 | awk '{ print $7 }' | grep time`
	;;
	33)	tijd=`ping -c 1 -w 1 10.33.255.254 | awk '{ print $7 }' | grep time`
	;;
	168)	tijd=`ping -c 1 -w 1 192.168.0.1  | awk '{ print $7 }' | grep time`
	;;
	99)	tijd=`ping -c 1 -w 1 10.99.99.1  | awk '{ print $7 }' | grep time`
	;;
	1)	case $derdebyte in
		62) tijd=`ping -c 1 -w 1 10.1.62.254 | awk '{ print $7 }' | grep time`	
		;;
		*) tijd=`ping -c 1 -w 1 10.1.$derdebyte.254 | awk '{ print $7 }' | grep time`	
		;;
		esac


	;;  # 10.1.x.y netwerken
	*)	echo "ip range $ip niet voorzien." 
		tijd=' '
	;;
	esac
	echo ${tijd:-xxx} | tr '\n' ' '
	$whereisiwconfig $wifiinterface | grep "Bit Rate" | sed -e s/"          Bit Rate="//g | sed -e s/"  Tx-Power="//g
fi
}

while true ; do sleep 1 ; getwifiinfo ; done



